name: Build & Push Docker Image to container image registry

on:
    release:
        types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3.5.0
        with:
          fetch-depth: 2

      #- name: Set up QEMU (We don't need QEMU, because we don't build images for platforms other than linux/amd64
      #  uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        id: tags
        run: echo ::set-output name=name::${GITHUB_REF##*/}

      - name: Generate Docker image metadata
        uses: docker/metadata-action@v4.6.0
        id: img_meta
        with:
          flavor: |
            latest=auto
          images: ghcr.io/${{ github.repository }}
          tags: |
            ${{ steps.tags.outputs.name }}
            latest

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./
          tags: ${{ steps.img_meta.outputs.tags }}
          labels: ${{ steps.img_meta.outputs.labels }}
          push: true
          cache-from: type=gha,mode=max
          cache-to: type=gha,mode=max

